main: me.redraskal.arcadia.Arcadia
name: ${project.name}
version: ${project.version}
author: redraskal
softdepend: [UltraCosmetics]

commands:
  spec:
    description: "Toggles Spectator Mode."
  setgame:
    description: "Sets the current game."